### 1. Import Necessary libraries

In [2]:
import pandas as pd
import keras
from sklearn.preprocessing import StandardScaler

## 2. Import Data

In [3]:
diabetes_data = pd.read_csv('diabetes.csv')
diabetes_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

## 3. Data Preparation

In [11]:
X = diabetes_data.drop('Outcome',axis = 1)
y = diabetes_data[['Outcome']]

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=12,stratify=y)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)  
X_test = scaler.transform(X_test)

### HYPERPARAMETER TUNING

#### List the Hyperparamaters we used so far....
1. Learning Rate
2. Epochs
3. Batches
4. Activation Functions
5. Optimizers
6. Loss Functions
7. Kernel Initializers

### ========================================================

In [5]:
!pip install scikeras

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Requirement already satisfied: scikit-learn>=1.4.2 in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from scikeras) (1.7.1)
Requirement already satisfied: keras>=3.2.0 in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from scikeras) (3.12.1)
Requirement already satisfied: ml-dtypes in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: optree in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (0.19.0)
Requirement already satisfied: namex in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: packaging in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (24.2)
Requirement already satisfied: absl-py in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (2.4.0)
Requirement already satisfied: numpy in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (2.2.6)
Requirement already satisfied: h5py in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (3.14.0)
Requirement already satisfied: rich in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.2.0->scikeras) (14.3.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.5.1)
Requirement already satisfied: scipy>=1.8.0 in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.15.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from optree->keras>=3.2.0->scikeras) (4.13.2)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.2.0->scikeras) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\john gabriel\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Hyperparameter all at once
#### This process is computationally expensive.

In [34]:
import numpy as np
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

from scikeras.wrappers import KerasClassifier 
##I am building a neural network model using Keras Functional API, and I am using GridSearchCV with KerasClassifier to find the best parameters for the model
from sklearn.model_selection import GridSearchCV, KFold

In [47]:
def create_model(learning_rate=0.001,dropout_rate=0.0,activation_function='relu', init='glorot_uniform',neuron1=8, neuron2=4):

    model = Sequential()
    model.add(Dense(neuron1,input_shape=(8,),kernel_initializer=init,activation=activation_function))
    model.add(Dropout(dropout_rate))
    model.add(Dense(neuron2,kernel_initializer=init,activation=activation_function))    
    model.add(Dropout(dropout_rate))
    model.add(Dense(1, activation='sigmoid'))
    
    optimizer = keras.optimizers.Adam(learning_rate=learning_rate)
    model.compile(loss='binary_crossentropy',optimizer=optimizer,metrics=['accuracy'])
    return model

In [48]:
model = KerasClassifier(model=create_model,verbose=1)

In [49]:
param_grid = {'model__learning_rate': [0.001, 0.01], 
               #if its model_lr = Just variable naming, but here it is model__learning_rate -> Navigate inside object
              'model__dropout_rate': [0.0, 0.2],
              'model__activation_function': ['relu', 'tanh'],
              'model__init': ['glorot_uniform', 'he_uniform'],
              'model__neuron1': [8, 16],
              'model__neuron2': [4, 8],
              'batch_size': [10, 20],
              'epochs': [10, 50]
             }

In [51]:
kfold = KFold(n_splits=3, shuffle=True, random_state=42)
grid = GridSearchCV(estimator=model,param_grid=param_grid,cv=kfold,verbose=10,n_jobs=-1)   # parallel processing 🔥

In [43]:
grid_result = grid.fit(X_train, y_train)

Fitting 3 folds for each of 256 candidates, totalling 768 fits

In [44]:
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']

for mean, std, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, std, param))

Best: 0.785039 using {'batch_size': 20, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.718309 (0.031681) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.739471 (0.027507) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.742643 (0.014511) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.729547 (0.041430) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.747577 (0.008646) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.760569 (0.014093) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.765471 (0.011961) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.750813 (0.007987) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.677547 (0.027625) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.700319 (0.051865) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.744277 (0.015465) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.726423 (0.017710) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.775243 (0.004017) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.729635 (0.004945) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.757317 (0.005174) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.755707 (0.003515) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.732911 (0.030313) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.726351 (0.049938) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.726351 (0.049938) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.729603 (0.026037) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.736203 (0.021672) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.757325 (0.010104) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.763837 (0.016185) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.750813 (0.011963) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.698780 (0.036436) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.664538 (0.028891) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.703507 (0.033222) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.731237 (0.015001) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.758975 (0.023160) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.773649 (0.033194) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.767081 (0.013165) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.750829 (0.017149) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.765479 (0.018159) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.762235 (0.014768) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.762227 (0.007933) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.765511 (0.017795) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.754097 (0.016219) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.745959 (0.017846) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.744325 (0.011647) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.755723 (0.020436) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.734553 (0.013519) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.749187 (0.009974) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.754073 (0.013953) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.755715 (0.020905) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.768779 (0.023588) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.741057 (0.006324) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.763861 (0.019441) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.747569 (0.022511) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.724749 (0.004952) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.757349 (0.008668) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.755699 (0.015942) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.745951 (0.011474) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.755739 (0.021784) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.760601 (0.017157) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.767129 (0.021654) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.757357 (0.018478) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.737765 (0.013209) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.737765 (0.008905) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.757349 (0.014762) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.747553 (0.002642) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.757357 (0.015693) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.765511 (0.016880) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.755715 (0.013535) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.752503 (0.027804) with: {'batch_size': 10, 'epochs': 10, 'model__activation_function': 'tanh', 'model__dropout_rate': 0.2, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.762195 (0.013172) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.757325 (0.002627) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.768731 (0.013954) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.731261 (0.014525) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.765463 (0.010731) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.721489 (0.022287) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.749139 (0.022511) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.744277 (0.025836) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.763845 (0.006005) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.758927 (0.016570) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.736171 (0.013514) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.750869 (0.027452) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.721457 (0.020523) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.719879 (0.008899) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}
0.723123 (0.014055) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 4}
0.729643 (0.025894) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.0, 'model__init': 'he_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 16, 'model__neuron2': 8}
0.768755 (0.022751) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 4}
0.750845 (0.017855) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 8, 'model__neuron2': 8}
0.763829 (0.015303) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 4}
0.755747 (0.021714) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.001, 'model__neuron1': 16, 'model__neuron2': 8}
0.760545 (0.022653) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 4}
0.760553 (0.018708) with: {'batch_size': 10, 'epochs': 50, 'model__activation_function': 'relu', 'model__dropout_rate': 0.2, 'model__init': 'glorot_uniform', 'model__learning_rate': 0.01, 'model__neuron1': 8, 'model__neuron2': 8}

In [45]:
results_df = pd.DataFrame(grid_result.cv_results_)
results_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_batch_size,param_epochs,param_model__activation_function,param_model__dropout_rate,param_model__init,param_model__learning_rate,param_model__neuron1,param_model__neuron2,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,5.045100,0.195312,0.493346,0.029431,10,10,relu,0.0,glorot_uniform,0.001,8,4,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.712195,0.682927,0.759804,0.718309,0.031681,228
1,5.440703,0.433157,0.464653,0.023351,10,10,relu,0.0,glorot_uniform,0.001,8,8,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.736585,0.707317,0.774510,0.739471,0.027507,185
2,4.871217,0.245826,0.490717,0.033397,10,10,relu,0.0,glorot_uniform,0.001,16,4,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.741463,0.760976,0.725490,0.742643,0.014511,181
3,5.543427,0.647505,0.474578,0.018647,10,10,relu,0.0,glorot_uniform,0.001,16,8,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.751220,0.765854,0.671569,0.729547,0.041430,208
4,5.541381,0.638789,0.447228,0.018382,10,10,relu,0.0,glorot_uniform,0.010,8,4,"{'batch_size': 10, 'epochs': 10, 'model__activ...",0.741463,0.741463,0.759804,0.747577,0.008646,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,19.563561,0.354163,0.258666,0.008562,20,50,tanh,0.2,he_uniform,0.001,16,8,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.756098,0.731707,0.764706,0.750837,0.013976,144
252,18.166126,0.287159,0.515541,0.246011,20,50,tanh,0.2,he_uniform,0.010,8,4,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.731707,0.736585,0.769608,0.745967,0.016835,164
253,17.083828,0.414435,0.243767,0.005796,20,50,tanh,0.2,he_uniform,0.010,8,8,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.780488,0.741463,0.759804,0.760585,0.015941,81
254,16.634895,0.406208,0.148231,0.005946,20,50,tanh,0.2,he_uniform,0.010,16,4,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.770732,0.731707,0.774510,0.758983,0.019348,90
255,15.595517,0.076874,0.151569,0.002884,20,50,tanh,0.2,he_uniform,0.010,16,8,"{'batch_size': 20, 'epochs': 50, 'model__activ...",0.760976,0.736585,0.774510,0.757357,0.015693,100

In [46]:
results_df.to_csv("results.csv")

## THE END!!